### ISSUE TITLE
How place a Shape in a Svg viexBox ?

### ISSUE THREAD

**Issue by bilibiliou** [mojs/mojs#137]
I viewed  [《An Introduction to mo.js》](https://css-tricks.com/introduction-mo-js/) 

In this article, I can't understand this sentence : 
"At some point, you’ll also be able to choose between using a div or SVG, which will be awesome, because it makes it much easier to create a scaling animation for mobile if you can place it with an SVG viewBox."

I dont know how place a shaps in an Svg viewBox，because the mo.js create a shape to padding a div[data-name=“mojs-shape”],

I cant place div[data-name=“mojs-shape”] in a Svg parent

I dont know how remove the div[data-name=“mojs-shape”] and place the shape in a SVG viewBox

**Comment by xavierfoucrier** [comment]
Hi @bilibiliou,

Sorry for the lonnnng delay.
We are cleaning some old issues right now.

The library animates the parent div and some of the SVG properties, like the `fill` attribute. You shouldn't have to rely on the SVG viewbox itself to place the object on screen, using only CSS will be sufficient. SVG viewbow is made to display part of the SVG, its like a cropping feature on an image.

In specific cases, it is recommended to put the `mojs-shape` inside a parent `div`, then style this parent to position your object on screen. You shouldn't directly style the `mojs-shape` element because it is managed by mojs itself.

I think that what **Sarah Drasner** wanted to say is that "as mojs uses SVG for animations, it fits the user screen without having to manage retina stuff".
