### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by bonjour12** [mojs/mojs#168]
All in the title.  I am starting a new project that requires  js animations, but but I am afraid this library isn't maintained anymore. anyone could confirm please?

**Comment by xavierfoucrier** [comment]
The v2 is still in progress: _Updated 4 months ago._ Many work to do since the next release. The current version is fully documented on http://mojs.io.

**Comment by arxpoetica** [comment]
@legomushroom feel like chiming in?

**Comment by abdullahraid** [comment]
This project is amazing and I can tell, I couldn't find such features in any other JS motion library anywhere. But I feel like it's not maintained and not really sure about its future so I'm a bit afraid of using it in one of my projects.

**Comment by ibbatta** [comment]
+1 (want know project status and updates)

**Comment by eltonmesquita** [comment]
Sorry but I wouldn't say a project is abandoned after a 6 months pause. Developers got a life too and  they can't always dedicate a great amount of time to a OSS project.

**Now hold on for a little preach:**
This is the kind of issue that doesn't help anyone, just cause a bad effect on the library. You want the developer(s) to dedicate more time to improve it? Help them solving the issues. This project has 70+ open issues and could use some help on this side so the developer can focus on releasing new and better features.
I strongly advice @bonjour12 to close this issue and cease anyone from commenting on it.

Sorry, but open source is hard. People should be aware of this.

**Comment by arxpoetica** [comment]
It's a legitimate question; no need for a defensive posture. A simple yes/no will be helpful. Thank you.

**Comment by ScoutsOut** [comment]
Opensource IS a big sacrifice but when you take a step back and keep in perspective how the majority of us are...we're introverts and when we get involved in a project, we obsess until we move onto the next thing ;)

So it's a fair question and instead of getting triggered, you could have displayed some empathy instead.

OpenSource is like a product to business folks and requires outstanding "customer service" otherwise, who the heck would want to support the project?

Some food for thought ;)

**Comment by xavierfoucrier** [comment]
See https://github.com/mojs/mojs/issues/201#issuecomment-474144899.
