### ISSUE TITLE
is it possible to move with cursor?

### ISSUE THREAD

**Issue by pobian** [mojs/mojs#172]
in case i have create one circle, how do i move this circle with cursor?

**Comment by xavierfoucrier** [comment]
I @pobian! Simple as that :

	let circle = new mojs.Shape({
	    left: 0,
	    top: 0,
	    shape: 'circle',
	    fill: 'transparent',
	    stroke: '#f6cc00',
	    strokeWidth: { 10 : 0 },
	    radius: { 0 : 30 },
	    duration: 1000,
	    delay: 500,
	    repeat: 500,
	    isForce3d: true
	}).play();

	document.addEventListener('mousemove', function (e) {
	  circle.tune({
	    x: e.clientX,
	    y: e.clientY,
	  })
	});

Note that you will need to initialize the x & y properties at startup, otherwise, the circle will stay at the top left of the window until the cursor is moved  :wink:

**Comment by abdullahraid** [comment]
@xavierfoucrier How about using `replay()` within the event trigger function instead of using `play()` right away? I believe this would play the animation only when the mouse is moving.

**Comment by xavierfoucrier** [comment]
I @abdullahraid! In fact, no.

The circle animation will be played 500 times, based on the `repeat` parameter. The event listener just `tune` the animation at the specified coordinates.

`replay()` allow you to replay the animation when its done: replaying this example will start the animation at 0 and repeat it 500 times. So, using `replay()` in the event listener instead of calling `play()` will replay the animation each time the mouse is moving, but the animation will be freezed when the mouse cursor is not moving: it depends what type of effect you want to do.

Hope that sound's clear to you :wink:

**Comment by abdullahraid** [comment]
Very true 😄 Thank you for your clarification @xavierfoucrier 

What I was trying to do is to play the animation when the mouse is moving only. Something like this would work:

```
let circle = new mojs.Shape({
    left: 0,
    top: 0,
    shape: 'circle',
    fill: 'transparent',
    stroke: '#f6cc00',
    strokeWidth: { 10: 0 },
    radius: { 0: 30 },
    duration: 1000,
    delay: 500,
    isForce3d: true
});

document.addEventListener('mousemove', function (e) {
    circle.tune({
        x: e.clientX,
        y: e.clientY
    }).play();
});
```

Have a nice day!

**Comment by xavierfoucrier** [comment]
Yep! Don't forget to remove the `delay` parameter for a better UX reactivity. Have a nice day too!

**Comment by xavierfoucrier** [comment]
Hi @abdullahraid!
If my answer seems relevant to you, you can close the issue. Thx! :+1:

**Comment by xavierfoucrier** [comment]
Hi @pobian!
If my answer seems relevant to you, you can close the issue. Thx! :+1:
