### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by javierojeda94** [mojs/mojs#183]
Hey guys... I'm just wondering if you have any plan to keep on this project? I don't see the documentation being updated and the last commit was almost a year ago.

So... What are the plans?

**Comment by philipzaengle** [comment]
so, um, is this dead?

**Comment by javierojeda94** [comment]
Hate that not even a single comment from the dev team... Nothing at all.

**Comment by Tomarnst** [comment]
I don't know ... but ... @xavierfoucrier seems to be quite willing to help out sometimes. But yeah I also would have loved to see this moving forward, maybe someone is willing to take it on.

**Comment by xavierfoucrier** [comment]
Yes I am still **watching** the project to help people and I still work with this library today.

It seems that the repository owner has moved to the Microsoft team and may be have no free time to work on mojs. Pull requests are **stacking since 2016** and this is a problem, but since there is no other owner that can review code and pull requests, this repository will stay like this. In addition, some resolved issues are still open and remain abandoned by their owner.

Anyway, mojs is not **dead** literally because there is a big community behind the project. My position is that @legomushroom may add admin contributors to help this library stay up to date.

**Comment by philipzaengle** [comment]
that would be great. Hey, @legomushroom - any thoughts on how to keep this going?

**Comment by javierojeda94** [comment]
I agree with that as well!!

**Comment by javierojeda94** [comment]
@legomushroom is this an option? I qould love to see this project move forward, please!

**Comment by xavierfoucrier** [comment]
See https://github.com/mojs/mojs/issues/201#issuecomment-474144899.
