### ISSUE TITLE
Problem with opacity easing

### ISSUE THREAD

**Issue by RomanSarvarov** [mojs/mojs#191]
I want to create a clap button like here: [https://codepen.io/ohansemmanuel/pen/dVdvJQ](https://codepen.io/ohansemmanuel/pen/dVdvJQ),
It works well except one thing: element with id "clap--count-total" is not visible by default (it appears only after a click).
How can I set it visible after page load and ease it after user's click?
I can set it manually by js, but I think there is a simply way which I just don't know.

**Comment by xavierfoucrier** [comment]
Hi @RomanSarvarov,

Do you have a codepen or code sample of your animation to show the problem?
I need that to understand what you mean.

Thanks 😉

**Comment by RomanSarvarov** [comment]
@xavierfoucrier https://codepen.io/ohansemmanuel/pen/dVdvJQ
Thank you.

**Comment by xavierfoucrier** [comment]
Ho ok I didn't understand that this codepen was yours! I will dive into your code tomorrow and give a feedback next. 👍

**Comment by xavierfoucrier** [comment]
Hi @RomanSarvarov,

In fact, the total clap count element is not visible because of some properties setted in your mojs object, especially **isShowStart** and **opacity**.

To show the element by default, you need to set `isShowStart: true` and `opacity: 1`: this will bring your animation element visible in the viewport.

In addition, your `span` is empty by default, that's why nothing is displayed on page load: you need to fill the element with a default value through javascript or html. For example: `<span id="clap--count-total" class="clap--count-total">1200</span>`

Finally, if you want to create a more complex animation for the total clap count text, you will need to build your timeline in another way.

Hope this help! :wink:

**Comment by xavierfoucrier** [comment]
@RomanSarvarov up

**Comment by RomanSarvarov** [comment]
@xavierfoucrier thank you!

**Comment by xavierfoucrier** [comment]
This fixed your problem? :smiley: 
If yes, you can **close the issue**. This will reduce the number of issues that stays open on this project.

Thanks!
