### ISSUE TITLE
Mojs prevent Angular from updating the view when model changed

### ISSUE THREAD

**Issue by wangzhenhui1992** [mojs/mojs#197]
### Mojs prevent Angular from updating the view when model changed.
- Angular: 
  - 5.x
- Mojs
  - //cdn.jsdelivr.net/mojs/latest/mo.min.js
- Code:
  ```
    <app-root></app-root>
    <script src="//cdn.jsdelivr.net/mojs/latest/mo.min.js"></script>
    <script src='//cdn.jsdelivr.net/mojs-player/latest/mojs-player.min.js'></script>
  ```
### detail
Everytime I updated the model of Angular components, the view was not updated until I click on the view.But if I delete the HTML below, it works.
```
    <script src="//cdn.jsdelivr.net/mojs/latest/mo.min.js"></script>
    <script src='//cdn.jsdelivr.net/mojs-player/latest/mojs-player.min.js'></script>
```

**Comment by Sandstedt** [comment]
Sounds like some problem with your build system. But would need more info what you mean by not updating  the view. Does mojs prevent your angular application to hot reload while saving a change in your code editor?

Can you try to embed the mojs script in your build system instead of linking it to a cdn?

Hadn't work with angular so not sure if their is some problem with the mojs library, but I  believe the problem is how you implement it.

**Comment by xavierfoucrier** [comment]
Hi @wangzhenhui1992,

Did you fixed your issue with Angular + mojs?

**Comment by wangzhenhui1992** [comment]
> Hi @wangzhenhui1992,
> 
> Did you fixed your issue with Angular + mojs?

@xavierfoucrier No, I have given up it....
