### ISSUE TITLE
Not working on IE

### ISSUE THREAD

**Issue by rajkanase** [mojs/mojs#255]
Hey Guys,

I have used **mojs** in one of my angular project. I want to **run this project on IE as well**. But it's not working in IE. I can see **only blank screen on browser pag**e. Please refer below image for same.
![image](https://user-images.githubusercontent.com/25950095/127285078-8566d651-9e2b-4963-86c3-2fd55716f936.png)
**Please check what my console says.**
![image](https://user-images.githubusercontent.com/25950095/127286473-76bf806b-77cc-4bcb-906b-87cf99953420.png)
**Please check where that error points to -** 
![image](https://user-images.githubusercontent.com/25950095/127286581-4ec826bf-7d22-467a-a3d8-4dbd533aa27f.png)
**About my IE**
![image](https://user-images.githubusercontent.com/25950095/127287701-5772369e-59e9-4660-8156-3db4614e7b6e.png)

When I visited [Npm Documentation of mojs](https://www.npmjs.com/package/@mojs/core/v/0.288.2#target-browsers), it says it supports IE9+. One more things to note here is when I visited git page of same [Git Doc of mojs](https://github.com/mojs/mojs#browser-support) I found, no IE mentioned in list. 

Please consider this as a request and let me know if this supports IE if yes then above which version? Any modifications do I need to make in my application? 
@legomushroom

**Comment by xavierfoucrier** [comment]
Hi @rajkanase,

Sorry but since `@mojs/core v1.0` has been released, we have dropped support for Internet Explorer.
The link to the NPM documentation you provide target version `0.288.2`, that was previously supported IE.

If you want to keep IE support in your application, we strongly recommend you to use `@mojs/core@0.288.2` instead of latest `v1.0`. You can find minified version here: https://unpkg.com/browse/@mojs/core@0.288.2/build/.

> See breaking changes: https://github.com/mojs/mojs/releases/tag/v1.0.0.

I am closing the issue :wink:

**Comment by rajkanase** [comment]
Hey @xavierfoucrier 

Thanks a lot for quick reply. That's my mistake. I didn't compare versions. Let me try using old version, if it won't break anything I can continue with it.
