### ISSUE TITLE
The file imported by cdn reports an error(a native html page)

### ISSUE THREAD

**Issue by deepalon** [mojs/mojs#260]
Uncaught TypeError: Cannot read properties of null (reading 'appendChild'). Error in core:10.

**Comment by xavierfoucrier** [comment]
Hi @deepalon,

Can you provide more informations?
How do you import the file, what's the context?

Without further informations it's almost, you guess, impossible to know what's going on.
Thanks! :wink:

**Comment by wxmwxm2021** [comment]
> Uncaught TypeError: Cannot read properties of null (reading 'appendChild'). Error in core:10.

Hi, as me know, that's just because you import this mo.js at <head></head>,
just advise you to do like this: you can try to put the import in the body, for example:
<body>
<dv>【here is you html element】<div>
<script src="https://cdn.jsdelivr.net/npm/@mojs/core"></script>
<script type="text/javascript">
【here is you javascript code】
</script>
</body>

After mine observation, I have found out the root cause of this problem: the mo html element that you want to init have not been
loaded successfully
That's all
