### ISSUE TITLE
Offset on click animations

### ISSUE THREAD

**Issue by bUxEE** [mojs/mojs#262]
Hello,

I have tried using the same example for on click animation  which is present in the documentation but I am getting an offset on the burst position:

Here is a fiddle:
https://jsfiddle.net/au7t1nr3/2/

**Comment by xavierfoucrier** [comment]
Hi @bUxEE,

This issue is more related to **how your code is running** than MoJS issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://github.com/mojs/mojs#developer.

A short answer to this issue is that you need to set the `left` / `top` offsets to `0`, by default `Burst` offsets equals `50%`.
> See https://mojs.github.io/api/modules/burst/#burst.

**Comment by bUxEE** [comment]
TY @xavierfoucrier,

quite dumb from my side, i tried to apply the position to the Shape object, missed those params for Burst. 

Thanks

**Comment by xavierfoucrier** [comment]
@bUxEE No problem! MoJS API is complex and can be hard to master at the beginning :wink:
