### ISSUE TITLE
Showcase code is not working

### ISSUE THREAD

**Issue by PricelessCode** [mojs/mojs#273]
In the main README.md file, seems like the code isn't working properly in the CodePen.

[Motion Graphics for the Web](https://codepen.io/sol0mka/full/ogOYJj/)
[Bubble Layout](https://codepen.io/sol0mka/full/yNOage/)

**Comment by xavierfoucrier** [comment]
Hi @PricelessCode 👋 

Thanks for pointing this out, unfortunately we don't have hand on @legomushroom codepens.

Despite the fact you access all the codepen codebase, those snippets have been built years ago.. so assembling part of code with the new version could lead to unrecoverable errors / issues.

I suggest that you start your animation from scratch or use a different "working" codepen.
We are really sorry about that.

> I remember @Sandstedt previously answered about broken codepens? 🤔

**Comment by Sandstedt** [comment]
@PricelessCode If I remember correctly, those pens where really hard to convert. But if you check the tutorials and the documentation site on https://mojs.github.io/, all those examples should work just fine.

**Comment by xavierfoucrier** [comment]
Thanks @Sandstedt 🙏 , I remember now.

Additional infos: at the time of writing this codepen, Oleg was using a minified version of mojs that was hosted on his private cloud, dropbox or something, and since this version is not reachable anymore, the codepen fails to run properly. I am seeing that in some cases there are bug syntax or missing code, and in this case we can do nothing.

I am closing this issue since, from my point of view, those pens are currently unrecoverable 🐛
