### ISSUE TITLE
Play the animation backwards when the playback is complete.

### ISSUE THREAD

**Issue by sharathdaniel** [mojs/mojs#48]
How can i achieve this? I tried `onPlaybackComplete () {}` method and it isn't working.

**Comment by Sandstedt** [comment]
I think you can use:
```repeat: 1, 
isYoyo: true ```

**Comment by legomushroom** [comment]
@sharathdaniel hi! Thanks for the issue and sorry about that. It happens because `Shape` module has `tween` and `timeline` at the same time, which controls its animation. When you call `play` - you are playing the `timeline` but the options are for tween, so you can either:
- use `timeline` object in options to pass the `onPlaybackComplete` http://codepen.io/sol0mka/pen/oLyGwa?editors=0011
- or `play` the `tween` instead of the `timeline` (which is by default) http://codepen.io/sol0mka/pen/rLKGkG?editors=0011

Both these variants create an infinite loop since `onPlaybackComplete` will fire every time after animation finishes so you might want to use `onComplete` callback instead http://codepen.io/sol0mka/pen/bZKoQZ?editors=0011

Hope it helps!
