### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by FrancosLab** [mojs/mojs#70]
Venturing into picking an animation library. 

Honestly have come down to choosing between Mo.js or Velocity.

Mainly will be doing UI animations but also have need for a few animations that mojs seems perfect for. 

The one thing that's keeping me back from picking mo.js is the lack of a getting started documentation any news on when this will be up? I think I may have read somewhere that you had a few drafts that needed proofreading, why not push the drafts to the repo and then commit for the proofread version? Just an idea. That way those of us interested can read through them even if they are not completely ready.

Love the style mo.js bring though, very well presented!

**Comment by legomushroom** [comment]
Hi @FrancosLab ! Thanks for the issue!

That's a great question. That version of getting started is deprecated - the proofreading was delayed and a lot of new modules and tools added, but most importantly, a library has changed a lot so that API's don't work anymore. Thus it will add much more harm than knowledge and will mess up things a lot. I know how frustrating it can be to start with some library without a decent guide! I will try to spend more time on that and maybe even create screencasts on the topic. That's just some crazy times for me with my relocation and new job search so my hands are full of other problems. 

Meanwhile, you can start with the [docs](https://github.com/legomushroom/mojs/tree/master/api) -  there are some basic codepen examples that might help, also you can checkout some of the tutorials on the [mojs.io](http://mojs.io/) website. And if you have any questions, please don't hesitate to ask me, I always happy to help!

Sorry and thanks! Cheers

**Comment by sdras** [comment]
I'm not sure if it will help or not, but I'm writing an intro article for CSS-Tricks right now. Though truthfully, it's mostly based off of what I've learned in the tutorials section of the site (which is quite excellent) along with some tips from @legomushroom. I hope to have it out in the next couple of weeks.

**Comment by zfrisch** [comment]
@legomushroom If you need help proofreading anything I would be happy to contribute some time to help. Also, I just get your letter in the mail, and it was much appreciated!

**Comment by legomushroom** [comment]
@sdras awesome!

**Comment by legomushroom** [comment]
@zfrisch thanks a lot!

**Comment by FrancosLab** [comment]
No need to apologize. Decided to go with mo.js after all! Took a read through the 2 modules, loving the declarative api. Look forward to contributing as well!

**Comment by legomushroom** [comment]
@FrancosLab yay!

**Comment by RobbertWolfs** [comment]
I needed, would like to help with updating the docs :). Still have to get to know mojs better but when helping maybe this wil also help me.

**Comment by legomushroom** [comment]
@RobbertWolfs sure! Anything helps!
